Coddin\IdentityProvider\Entity\OpenIDConnect\OAuthClient:
  type: entity
  table: oauth_client
  repositoryClass: Coddin\IdentityProvider\Repository\OAuthClientRepository
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: AUTO
  fields:
    externalId:
      type: string
      length: 255
    externalIdReadable:
      type: string
      length: 255
    name:
      type: string
      length: 255
    displayName:
      type: string
      length: 255
    isConfidential:
      type: boolean
    isPkce:
      type: boolean
    secret:
      type: string
      length: 255
    creationWebhookUrl:
      type: string
      nullable: true
    createdAt:
      type: datetime_immutable
    updatedAt:
      type: datetime_immutable
  oneToMany:
    redirectUris:
      targetEntity: OAuthRedirectUri
      mappedBy: oAuthClient
    oAuthAuthorizationCodes:
      targetEntity: OAuthAuthorizationCode
      mappedBy: oAuthClient
    oAuthAccessTokens:
      targetEntity: OAuthAccessToken
      mappedBy: oAuthClient
    userOAuthClients:
      targetEntity: UserOAuthClient
      mappedBy: oAuthClient
