Coddin\IdentityProvider\Entity\OpenIDConnect\PasswordResetRequest:
  type: entity
  table: password_reset_request
  repositoryClass: Coddin\IdentityProvider\Repository\PasswordResetRequestRepository
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: AUTO
  fields:
    token:
      type: string
      length: 255
    usedAt:
      type: datetime_immutable
      nullable: true
    createdAt:
      type: datetime_immutable
    validUntil:
      type: datetime_immutable
  manyToOne:
    user:
      targetEntity: User
      joinColumn:
        name: user_id
        referencedColumnName: id
        nullable: false
