Coddin\IdentityProvider\Entity\OpenIDConnect\User:
  type: entity
  table: user
  repositoryClass: Coddin\OpenIDConnect\Infrastructure\Persistence\Doctrine\Dbal\UserDbalRepository
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      length: 100
    uuid:
      type: string
      length: 36
    email:
      type: string
      length: 100
    password:
      type: string
      length: 132
    roles:
      type: json
    createdAt:
      type: datetime_immutable
    updatedAt:
      type: datetime_immutable
  oneToMany:
    oAuthAuthorizationCodes:
      targetEntity: OAuthAuthorizationCode
      mappedBy: user
    oAuthAccessTokens:
      targetEntity: OAuthAccessToken
      mappedBy: user
    userOAuthClients:
      targetEntity: UserOAuthClient
      mappedBy: user
