api:
  prefix: /identity
  resource: 'routes/identity/routes.yaml'

account:
  prefix: /account
  resource: 'routes/account/routes.yaml'

authentication:
  resource: 'routes/authentication/routes.yaml'

home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /login
    permanent: true
