services:
  Coddin\IdentityProvider\Repository\OAuthAccessTokenRepository:
    class: Coddin\IdentityProvider\Repository\Dbal\OAuthAccessTokenDbalRepository

  Coddin\IdentityProvider\Repository\OAuthAuthorizationCodeRepository:
    class: Coddin\IdentityProvider\Repository\Dbal\OAuthAuthorizationCodeDbalRepository

  Coddin\IdentityProvider\Repository\OAuthClientRepository:
    class: Coddin\IdentityProvider\Repository\Dbal\OAuthClientDbalRepository

  Coddin\IdentityProvider\Repository\OAuthRefreshTokenRepository:
    class: Coddin\IdentityProvider\Repository\Dbal\OAuthRefreshTokenDbalRepository

  Coddin\IdentityProvider\Repository\UserOAuthClientRepository:
    class: Coddin\IdentityProvider\Repository\Dbal\UserOAuthClientDbalRepository

  Coddin\IdentityProvider\Repository\UserRepository:
    class: Coddin\IdentityProvider\Repository\Dbal\UserDbalRepository

  # Doctrine data fixtures
  Coddin\IdentityProvider\DataFixtures\:
    resource: '%kernel.project_dir%/src/DataFixtures'
    tags: [ 'doctrine.fixtures.orm' ]
