coddin_identity_provider.idp:
  prefix: /identity
  resource: 'routes/identity/routes.yaml'

coddin_identity_provider.account:
  prefix: /account
  resource: 'routes/account/routes.yaml'

coddin_identity_provider.authentication:
  resource: 'routes/authentication/routes.yaml'

coddin_identity_provider.home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /login
    permanent: true
