services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Coddin\IdentityProvider\Repository\Dbal\OAuthAccessTokenDbalRepository:
    public: true
  Coddin\IdentityProvider\Repository\Dbal\OAuthAuthorizationCodeDbalRepository:
    public: true
  Coddin\IdentityProvider\Repository\Dbal\OAuthClientDbalRepository:
    public: true
  Coddin\IdentityProvider\Repository\Dbal\OAuthRefreshTokenDbalRepository:
    public: true
  Coddin\IdentityProvider\Repository\Dbal\PasswordResetRequestDbalRepository:
    public: true
  Coddin\IdentityProvider\Repository\Dbal\UserDbalRepository:
    public: true
  Coddin\IdentityProvider\Repository\Dbal\UserOAuthClientDbalRepository:
    public: true

  Coddin\IdentityProvider\Service\MultiFactorAuthentication\Method\Client\SmsClientInterface:
    class: Tests\Helper\NullSmsClient
