imports:
  - { resource: 'services/flysystem.yaml' }
  - { resource: 'services/oauth_server.yaml' }
  - { resource: 'services/parameters.yaml' }
  - { resource: 'services/repositories.yaml' }
  - { resource: 'services/serializer.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Coddin\IdentityProvider\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'

  # Set services by tag
  Coddin\IdentityProvider\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  Coddin\IdentityProvider\DataFixtures\:
    resource: '../src/DataFixtures'
    tags: [ 'doctrine.fixtures.orm' ]

  # Events
  Coddin\IdentityProvider\EventListener\UserLocaleListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 110 }

  Coddin\IdentityProvider\EventSubscriber\RequestConstraintExceptionSubscriber:
    tags:
      - { name: idp.request_invalid_exception, event: kernel.exception }

  Coddin\IdentityProvider\EventListener\LogoutListener:
    tags:
      - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LogoutEvent, dispatcher: security.event_dispatcher.main }

  # Service wiring
  Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory: ~

  Coddin\IdentityProvider\Request\Validation\RequestObjectResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }
