well_known:
  path: /.well-known/openid-configuration
  methods: GET
  controller: IdentityProvider\Controller\Identity\AuthorizationController::wellKnown

jwks:
  path: /.well-known/jwks
  methods: GET
  controller: IdentityProvider\Controller\Identity\AuthorizationController::wellKnownJsonWebKeys

authorize:
  path: /authorize
  methods: GET
  controller: IdentityProvider\Controller\Identity\AuthorizationController::authorize

token:
  path: /token
  methods: POST
  controller: IdentityProvider\Controller\Identity\AuthorizationController::token

introspect:
  path: /introspect
  methods: POST
  controller: IdentityProvider\Controller\Identity\AuthorizationController::introspect

end_session:
  path: /endsession
  methods: GET
  controller: IdentityProvider\Controller\Identity\AuthorizationController::endSession
